#use este arquivo para aplicar o secret antes de subir a application: kubectl apply -f screts.yaml
apiVersion: v1
kind: Secret
metadata:
  namespace: wordpress
  name: mysql-secret
type: Opaque
stringData:
  password-db-root: root123
  password-user: user123

