apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: wp-site
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wordpress
  project: default  
  source:
    repoURL: 'git@github.com:uzieljr/pv-wordpress.git'
    path: app-wordpress-helm
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      #- Replace=true
