apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:4.8-apache
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: wordpress-mysql
          - name: WORDPRESS_DB_NAME
            value: wordpress-mysql
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
#            value: wordpress-2020            
              secretKeyRef:
                name: mysql-secret
                key: password-db-root
        volumeMounts:
          - mountPath: /var/www/html
            name: wordpress-volume        
      volumes:
        - name: wordpress-volume
          persistentVolumeClaim:
            claimName: wordpress
